name: green_urban_grow
description: Urban gardening app for small spaces
version: 1.0.0
environment:
  sdk: ">=3.0.0 <4.0.0"
  
dependencies:
  flutter:
    sdk: flutter
  url_launcher: ^6.1.11

flutter:
  uses-material-design: true
  assets:
    - assets/care_tips.json
