name: green_urban_grow
description: Urban gardening app for small spaces
version: 1.0.0
environment:
  sdk: ">=2.17.0 <3.0.0"
  
dependencies:
  flutter:
    sdk: flutter

flutter:
  uses-material-design: true
