name: Prebuilt APK CI

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  upload-apk:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Upload APK artifact (if exists)
        uses: actions/upload-artifact@v4
        with:
          name: GreenUrbanGrow-APK
          path: android/app/build/outputs/apk/release/app-release.apk
