name: Flutter Build APK
on:
  push:
    branches: [ main ]

jobs:
  build-android:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.16.9'
      - run: flutter pub get
      - run: flutter build apk --release
      - uses: actions/upload-artifact@v4
        with:
          name: green-urban-grow-app
          path: build/app/outputs/flutter-apk/app-release.apk

  # iOS build commented out until proper iOS configuration is added
  # build-ios:
  #   runs-on: macos-latest
  #   steps:
  #     - uses: actions/checkout@v4
  #     - uses: subosito/flutter-action@v2
  #       with:
  #         flutter-version: '3.16.9'
  #     - run: flutter pub get
  #     - run: flutter build ios --release --no-codesign
  #     - uses: actions/upload-artifact@v4
  #       with:
  #         name: green-urban-grow-ios
  #         path: build/ios/ipa/
