name: Build Flutter APK & IPA

on:
  push:
    branches:
      - main

jobs:
  android:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.7'
      - name: Get dependencies
        run: flutter pub get
      - name: Build Android APK
        run: flutter build apk --debug
      - name: Upload Android APK
        uses: actions/upload-artifact@v3
        with:
          name: GreenUrbanGrow-debug-apk
          path: build/app/outputs/flutter-apk/app-debug.apk

  ios:
    runs-on: macos-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.7'
      - name: Get dependencies
        run: flutter pub get
      - name: Build iOS IPA
        run: flutter build ipa --no-codesign
      - name: Upload iOS IPA
        uses: actions/upload-artifact@v3
        with:
          name: GreenUrbanGrow-debug-ipa
          path: build/ios/ipa/*.ipa
